### ISSUE TITLE
Cartan subalgebras exist

### ISSUE THREAD

**Issue by ocfnash** [leanprover-community/mathlib4#10065]
We should prove that semisimple Lie algebras have Cartan subalgebras. Furthermore we should prove this making only weak assumptions on the coefficients.

**Comment by jcommelin** [comment]
#10628 defines the rank of a Lie algebra, and proves existence of regular elements

**Comment by jcommelin** [comment]
Closed by #12297

**Comment by jcommelin** [comment]
Done
