### ISSUE TITLE
Refactor/remove BilinForm

### ISSUE THREAD

**Issue by mans0954** [leanprover-community/mathlib4#10553]
There seems to be broad agreement that in the long term `structure BilinForm` should not exist - instead we should use `M →ₗ[R] M →ₗ[R] R`.

Many `BilinForm` results already have equivalents e.g. following #9485, many of the results in `LinearAlgebra/Matrix/BilinearForm` are just wrappers around results in `LinearAlgebra/Matrix/SesquilinearForm`.

One possible objection to removing `BilinForm` altogether at this stage is that it supports non-commutative semirings, which `M →ₗ[R] M →ₗ[R] R` does not support without further assumptions.

Zulip discussion: 

- https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Quadratic.20Maps/near/395767687
- https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/.60bilinear_form.60

Related issues/PRs:

-  #7581
-  #9485
- #10097
- #10238
- #10422
- #10424
- #10432
- #11032
- #11057
- #11078
- https://github.com/leanprover-community/mathlib/issues/15907

**Comment by eric-wieser** [comment]
> One possible objection to removing `BilinForm` altogether at this stage is that it supports non-commutative semirings,

I don't think this is meaningfully true; the axiomatization [is basically nonsense](https://math.stackexchange.com/q/1069189/1896) for non-commutative semirings, so while we may support `BilinForm R` when `Semiring R`, it's not a "bilinear form" any more
