### ISSUE TITLE
Porting note: removed `@[nolint has_nonempty_instance]`

### ISSUE THREAD

**Issue by pitmonticone** [leanprover-community/mathlib4#10927]
Classifies porting notes claiming `removed @[nolint has_nonempty_instance]`.

### Examples 

https://github.com/leanprover-community/mathlib4/blob/d3dbfd96d551bb78ae75db33df18a386bda9b81b/Mathlib/AlgebraicTopology/SimplicialObject.lean#L39-L44

https://github.com/leanprover-community/mathlib4/blob/d3dbfd96d551bb78ae75db33df18a386bda9b81b/Mathlib/AlgebraicTopology/SimplicialObject.lean#L411-L415

https://github.com/leanprover-community/mathlib4/blob/d3dbfd96d551bb78ae75db33df18a386bda9b81b/Mathlib/CategoryTheory/CommSq.lean#L112-L121

**Comment by grunweg** [comment]
This is a special case of porting notes caused by #5171; does it make sense to reference that issue instead?

**Comment by grunweg** [comment]
I have changed all references to point to #5171 instead; let me close this issue. Thanks for classifying all these!
