### ISSUE TITLE
Mem instance for lists

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/mathlib4#11]
Right now we have `infix:50 " ∈ " => mem` in Data.List.Basic, and also a `∈` notation class Mem used for sets. I tried to replace the list notation with an instance of Mem and it broke all the proofs :-( What am I doing wrong? Obviously I could just fix all the proofs one by one and make them all longer, but I was not sure this would be welcome as a PR and I suspect I'm missing a trick.

**Comment by gebner** [comment]
Replacing the list-only notation by a type-class is definitely welcome.  If it turns out that this breaks stuff, then that's a valuable learning experience and exactly what mathlib4 is for.

But please submit a PR.  It's hard to figure out what's going wrong from a frowning smiley.
