### ISSUE TITLE
trans tactic does not use `HEq.trans`

### ISSUE THREAD

**Issue by semorrison** [leanprover-community/mathlib4#1119]
See example in `Mathlib.CategoryTheory.Functor.FullyFaithful`.

**Comment by siddhartha-gadgil** [comment]
This was my mistake in assuming types equal in transitivity and using a single relation `r`. Should model on the `Trans` class and assume separate relations. Will try to fix.

**Comment by siddhartha-gadgil** [comment]
It looks like `trans` needs serious repairs. Will work on it.
