### ISSUE TITLE
Shake telling me to replace import that is necessary.

### ISSUE THREAD

**Issue by BoltonBailey** [leanprover-community/mathlib4#11554]
In PR #11542, which splits off a `Data.List.InsertNth` file from `Data.List.Basic` I am experiencing the following CI error

```
/usr/bin/env LEAN_ABORT_ON_PANIC=1 lake exe shake --gh-style
info: [1/3] Building Shake.Main
info: [2/3] Compiling Shake.Main
info: [3/3] Linking shake
Warning: ./././Mathlib/Data/List/Lemmas.lean:[7](https://github.com/leanprover-community/mathlib4/actions/runs/8366890818/job/22908083269?pr=11542#step:23:8):1: warning: unused import (use `lake exe shake --fix` to fix this, or `lake exe shake --update` to ignore)
Warning: ./././Mathlib/Data/List/Lemmas.lean:[8](https://github.com/leanprover-community/mathlib4/actions/runs/8366890818/job/22908083269?pr=11542#step:23:9):1: warning: import #[Mathlib.Data.List.Basic] instead
./././Mathlib/Data/List/Lemmas.lean:
  remove #[Mathlib.Data.List.InsertNth]
  add #[Mathlib.Data.List.Basic]
Error: The process '/usr/bin/env' failed with exit code 1
```

But this is definitely not right. `insertNth_succ_cons`, for example, is used in `Lemmas`, and was moved to the new file, so it is necessary to import the file, and if the old file is imported instead, there is an error.

I am just going to run the recommended command, but someone should get to the bottom of this error.

**Comment by BoltonBailey** [comment]
Here is me trying to run the `lake exe shake --update` command as I was told to.
```
boltonbailey@starlight mathlib4 % lake exe shake --update
info: [1/3] Building Shake.Main
info: [2/3] Compiling Shake.Main
info: [3/3] Linking shake
There are out of date oleans. Run `lake build` or `lake exe cache get` first
boltonbailey@starlight mathlib4 % lake exe cache get
Attempting to download 2821 file(s)
Downloaded: 2821 file(s) [attempted 2821/2821 = 100%] (100% success)
Decompressing 4333 file(s)
unpacked in 3293 ms
boltonbailey@starlight mathlib4 % lake exe shake --update
There are out of date oleans. Run `lake build` or `lake exe cache get` first
boltonbailey@starlight mathlib4 % lake build
... Starts building thousands of files
```
It is a bit annoying that I have to build all of this to fix this problem.

**Comment by digama0** [comment]
If you run `shake` with out of date oleans, it will give very wrong answers, so yes it is a prerequisite that you have up to date oleans. Usually you would already have them available assuming you are fixing a shake error reported in CI, because CI has to build the oleans before running shake anyway.

**Comment by BoltonBailey** [comment]
Hmm, that's interesting. As you can see, I did run `lake exe cache get`. Shouldn't that have retrieved the oleans I needed to make this error message not appear?

**Comment by digama0** [comment]
This issue is stale, closing. (Lots of things have changed in `shake` since this was written, if it still occurs please give a new reproduction.)
