### ISSUE TITLE
Three bugs in `zify`

### ISSUE THREAD

**Issue by hrmacbeth** [leanprover-community/mathlib4#1576]
See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/zify.20bugs.3F).

**Comment by thorimur** [comment]
Just tested, and these all seem to be fixed by now! Can anyone else replicate?

**Comment by hrmacbeth** [comment]
Agreed!

For a partial record of when this happened, on 367e5e6965fa4a8bdc99c511f07d6de4a5623d3b (from March 8) the first two bugs are still there and the third has already been fixed.
