### ISSUE TITLE
The suggestion syntax for to_additive with another attribute does not work

### ISSUE THREAD

**Issue by MJ141592** [leanprover-community/mathlib4#20181]
I followed the recommended syntax for correcting the first case below, and got the second error - it should not have the square brackets on 'simp'. I'm being helped by Yael Dillies.

```
import Mathlib.Algebra.Group.ZeroOne
import Mathlib.Tactic.Common

@[simp,to_additive]
/-
The source declaration one_eq_one was given the simp-attribute(s) [simp] before calling
@[to_additive]. The preferred method is to use `@[to_additive (attr := [simp])]` to apply the
attribute to both one_eq_one and the target declaration zero_eq_zero.
note: this linter can be disabled with `set_option linter.existingAttributeWarning false`
-/
lemma one_eq_one {α : Type*} [One α] : (1 : α) = 1 := rfl

@[to_additive (attr := [simp])] -- unexpected token '['; expected ')'
lemma one_eq_one' {α : Type*} [One α] : (1 : α) = 1 := rfl
```

@fpvandoorn

**Comment by fpvandoorn** [comment]
The syntax is `@[to_additive (attr := simp)]`. Is this written somewhere in Mathlib?

**Comment by YaelDillies** [comment]
> Is this written somewhere in Mathlib?

What's "this"? the incorrect error message (which is indeed in mathlib) or documentation for the correct syntax (in which case I haven't seen such documentation, but might have missed it)?

**Comment by fpvandoorn** [comment]
Ah, I didn't realize that the comment was the error message. I'll fix it.

**Comment by fpvandoorn** [comment]
The `attr := ...` syntax is with a few examples in the documentation for `to_additive` (though I realize that this documentation doesn't easily show up when mousing over the attribute).

**Comment by MJ141592** [comment]
Thank you!
