### ISSUE TITLE
`linarith` not ignoring irrelevant (in)equalities

### ISSUE THREAD

**Issue by mo271** [leanprover-community/mathlib4#2610]
see https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/linarith.20and.20ENNReal and the mwe of @eric-wieser there:

```lean
import Mathlib.Tactic.Linarith

example : 0 ≤ 1 := by linarith -- ok

example (s : Set ℕ) (h : s = ∅) : 0 ≤ 1 :=
by linarith
/-
failed to synthesize
  AddGroup (Set ℕ)
-/
```
Seems like `linarith` should ignore (in)equalities in the context it doesn't get.

**Comment by dwrensha** [comment]
I ran into this problem recently too: https://github.com/dwrensha/math-puzzles-in-lean4/blob/f79693080e1a43c3d9f82098ebfd26c28abadaed/MathPuzzles/Usa1998Q5.lean#L74

**Comment by mo271** [comment]
I see, you used the same workaround: `clear` the interfering lemmas before invoking `linarith`.
