### ISSUE TITLE
Move some docstrings from doc_commands.lean closer to their implementations

### ISSUE THREAD

**Issue by lakesare** [leanprover-community/mathlib4#456]
The docs for `cc`, `conv`, `simp` are in the `doc_commands.lean` file in Mathlib 3 ([documentation](https://leanprover-community.github.io/mathlib_docs/tactic/doc_commands.html#tactic_doc.tactic.cc%20(congruence%20closure)), [code](https://github.com/leanprover-community/mathlib/blob/master/src/tactic/doc_commands.lean#L303)).  
I think we'll want to migrate these docstrings & `add_tactic_doc` commands closer to the actual tactic implementations in Mathlib 4?

**Comment by digama0** [comment]
Yes, that was a hack to attach doc strings to definitions from lean 3 core during the time that lean 3 was frozen and so we couldn't just add the doc strings directly to the implementation. Of course in the reimplementation we can put the doc string where it belongs. (In the case of `conv` and `simp` though the tactic already exists in lean 4 core, with a docstring, so if you want to migrate the lean 3 docstring you will have to merge the contents with what is already there and PR the result to lean4.)
