### ISSUE TITLE
Tracking issue for mysterious slowdowns

### ISSUE THREAD

**Issue by kim-em** [leanprover-community/mathlib4#5028]
Please link to this issue from a "Porting note" when a declaration is mysteriously significantly slower than in mathlib3.

**Comment by semorrison** [comment]
This [link](https://github.com/search?q=repo%3Aleanprover-community%2Fmathlib4%20https%3A%2F%2Fgithub.com%2Fleanprover-community%2Fmathlib4%2Fissues%2F5028&type=code) searches for references to this issue in the source code.

**Comment by fpvandoorn** [comment]
This instance of this issue is currently being removed by #17832
