### ISSUE TITLE
`use` does not work with the goal type

### ISSUE THREAD

**Issue by Ruben-VandeVelde** [leanprover-community/mathlib4#5072]
This fails:
```
example (n : Nat) : Nat := by
  use n
```
though it worked in mathlib3.

**Comment by semorrison** [comment]
This [link](https://github.com/search?q=repo%3Aleanprover-community%2Fmathlib4%20https%3A%2F%2Fgithub.com%2Fleanprover-community%2Fmathlib4%2Fissues%2F5072&type=code) searches for references to this issue in the source code.

**Comment by kmill** [comment]
I've started by making `use` support this, and I've added a `use!` that is almost the same as the original mathlib3 `use`. #5350
