### ISSUE TITLE
`simpNF` should ignore `dsimp`/`rfl` lemmas.

### ISSUE THREAD

**Issue by joneugster** [leanprover-community/mathlib4#5081]
See [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/!4.232104.20simpNF.20error.20in.20other.20files/near/355279033).

The `simpNF` linter should not trigger on `dsimp` lemmas, i.e. on lemmas that are proven by `rfl`, as these are considered always worth keeping in the simp-set, even if the LHS simplifies.

**Comment by semorrison** [comment]
This [link](https://github.com/search?q=repo%3Aleanprover-community%2Fmathlib4%20https%3A%2F%2Fgithub.com%2Fleanprover-community%2Fmathlib4%2Fissues%2F5081&type=code) searches for references to this issue in the source code.

**Comment by urkud** [comment]
These lemmas are worth keeping if the LHS simplifies by non-dsimp lemmas.

**Comment by semorrison** [comment]
This issue is already being tracked in Std: https://github.com/leanprover/std4/issues/86.
