### ISSUE TITLE
Porting note: `ext` does not look through definitions, so we need more `ext` lemmas

### ISSUE THREAD

**Issue by kim-em** [leanprover-community/mathlib4#5229]
Classifies porting notes claiming: 

> added `ext` lemma
> added `@[ext]`
### Links

- #11182: categorises removal of  `@[ext]`.
- #11041: categorises other failures of `ext`.
- #10756: categorises general addition of `theorem`s

### Notes

We could either provide some automation to generate the additional `ext` lemmas we need now, or work out how to make `ext` more powerful.

See discussion on zulip: [1](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/power-up.20for.20ext).

**Comment by semorrison** [comment]
This [link](https://github.com/search?q=repo%3Aleanprover-community%2Fmathlib4%20https%3A%2F%2Fgithub.com%2Fleanprover-community%2Fmathlib4%2Fissues%2F5229&type=code) searches for references to this issue in the source code.
