### ISSUE TITLE
CI should check for noisy files

### ISSUE THREAD

**Issue by semorrison** [leanprover-community/mathlib4#5411]
E.g. in #5271 I replaced a number of calls to `ring` with `ring_nf`, as they were emitting "Try this" messages.

There was such a check in mathlib3, but I don't immediately see where or how this worked.

**Comment by digama0** [comment]
The error report is here:

https://github.com/leanprover-community/mathlib/blob/57f9349f2fe19d2de7207e99b0341808d977cdcf/scripts/detect_errors.py#L26-L30

but I don't see who is writing the `.noisy_files` file.

**Comment by semorrison** [comment]
Closed by #5396, with a simpler solution!
