### ISSUE TITLE
Error on non-Debian Linux distros and VS Code: unknown package

### ISSUE THREAD

**Issue by pevogam** [leanprover-community/mathlib4#7339]
Hi all,

I have followed the exact instructions on how to install Lean on VS Code I could find on https://leanprover-community.github.io/install/linux.html which also happen to be the instructions [specified for this project](https://github.com/leanprover-community/mathlib4#installation) and despite my best effort when I try to import modules (e.g. here `data`) from mathlib4 I get:
```
unknown package 'data'
You might need to open '' as a workspace in your editor
```
From what I can gather in the official instruction above there is no mention that `mathlib4` needs separate installation steps and the documentation suggests that I should have been installed together with the VS Code extension and/or the main `elan-init.sh` step. Otherwise I would have expected separate instructions in the link above.

Am I missing something obvious here? Is there some path environment variable I can use to just set the path to the mathlib library if I simply clone it or documentation about how to do this I have missed?

Thanks in advance.

**Comment by pevogam** [comment]
Just to add: I believe this is a Github issue because if I was right above it indicates lack of sufficient documentation on how to do this and something we could try and fix (I am willing to contribute if you would prefer so).

**Comment by pevogam** [comment]
Indeed, just a bit later I realized that all the imports have been renamed in lean 4 (which I guess while breaking a lot of old compatibility is justifiable by the major version counter) but unfortunately encountered the very same problem importing the newer modules. I even tried manually placing the library and then separate lean files and trying to import them as:
```
[pevogam@vagrant experiments]$ find -maxdepth 2
.
./Test
./Test/test.lean
./Mathlib
./Mathlib/Util
./Mathlib/Algebra
./Mathlib/Data
./Mathlib/Lean
./Mathlib/Deprecated
./Mathlib/CategoryTheory
./Mathlib/Analysis
./Mathlib/Mathport
./Mathlib/Control
./Mathlib/Logic
./Mathlib/Order
./Mathlib/InformationTheory
./Mathlib/Geometry
./Mathlib/AlgebraicGeometry
./Mathlib/Combinatorics
./Mathlib/MeasureTheory
./Mathlib/ModelTheory
./Mathlib/RepresentationTheory
./Mathlib/Tactic.lean
./Mathlib/Topology
./Mathlib/LinearAlgebra
./Mathlib/RingTheory
./Mathlib/Dynamics
./Mathlib/Probability
./Mathlib/SetTheory
./Mathlib/GroupTheory
./Mathlib/NumberTheory
./Mathlib/Init
./Mathlib/Testing
./Mathlib/AlgebraicTopology
./Mathlib/Computability
./Mathlib/Tactic
./Mathlib/Condensed
./Mathlib/FieldTheory
./imports.lean
./test2.lean
./exploration.lean
```
where
```
[pevogam@vagrant experiments]$ cat imports.lean 
import test2
import Test.test
```
results in `unknown package 'test2'` or if I comment out the first line in `unknown package 'Test'`. The same happens for the `Mathlib` I manually placed as a folder within the project and any out-of-the-blue `Mathlib` folder I try to import globally that should have been installed somewhere.

Note that I copied the folder after I could not important any supposedly preinstalled package. Any expressions with built-in keywords work fine with the Lean interpreter.

I originally tried using `mathlib4.Mathlib` as well as  `Mathlib`  in an extra file in cloned Lean examples repo (I hope this didn't mess up anything, I still installed the VS Code plugin with the single recommended click). The above was then my attempt to move to a separate project that I would open as folder in VS Code. No module could be imported, preinstalled, manually copied, manually created, or otherwise.

**Comment by alexjbest** [comment]
Did you follow the instructions in https://leanprover-community.github.io/install/project.html (linked at the bottom of the link in your first post above)?
In general copy-pasting mathlib to a new directory will not produce a workable tree.
Mathlib and other lean dependencies are managed by lake, a program installed with lean. And the dependencies are managed for you based on a `lakefile.lean` and other auxilliary files in your project.

Are you trying to clone and work on mathlib or create a project with mathlib as a dependency?

**Comment by alexjbest** [comment]
Also I should say that Lean doesn't really follow the traditional semver, its more like major version number is a complete rewrite with little guarenteed backwards compatibility at all. middle number is possibly breaking changes also and maybe only the smallest number is bugfixes etc.

**Comment by pevogam** [comment]
> Did you follow the instructions in https://leanprover-community.github.io/install/project.html (linked at the bottom of the link in your first post above)? In general copy-pasting mathlib to a new directory will not produce a workable tree, neither will any other manual approach.

I tried the exact instructions and after I could not find the library by importing it (and read a page about importing lean modules), I decided to try these manual steps as a last resort.

> Mathlib and other lean dependencies are managed by lake, a program installed with lean. And the dependencies are managed for you based on a `lakefile.lean` that you write and other auxilliary files in your project (that are not really to be human edited).
> 
> Are you trying to clone and work on mathlib or create a project with mathlib as a dependency?

Just trying out a simple standalone project that needs a few Mathlib imports. I just pushed a bit harder and got it working with a bash script like
```
$ cat new_workspace.bash 
workspace=$1
project=$2

lake +leanprover/lean4:nightly-2023-02-04 new ${workspace} math
cd ${workspace}
lake update
lake exe cache get
mkdir ${project} || echo "Create project manually in the new worskpace"

echo "Workspace created"
```
that could be a simpler alternative to the somewhat overlapping description in these two sources:

https://leanprover-community.github.io/install/project.html
https://github.com/leanprover-community/mathlib4/wiki/Using-mathlib4-as-a-dependency

Considering how easy it was to run Lean directly by installing an add-on with VS Code I thought installing the mathlib4 would already be available but it seems I was wrong and I apologize for costing you some time here. In any case regarding the two sources above I would recommend [this change](https://github.com/leanprover-community/mathlib4/pull/7441), let me know what you think.

> Also I should say that Lean doesn't really follow the traditional semver, its more like major version number is a complete rewrite with little guarenteed backwards compatibility at all. middle number is possibly breaking changes also and maybe only the smallest number is bugfixes etc.

Good to know, I already expected breaking changes from the major version increment.

**Comment by pevogam** [comment]
The suggested change wasn't reviewed, merged or rejected so I expected the related issue to be open and thus tracked properly until then.

**Comment by alexjbest** [comment]
You'll need to tag that issue with awaiting-review if you want it to show up on the review queue that people look at (see https://leanprover-community.github.io/contribute/index.html#lifecycle-of-a-pr). As there are ~600 open PRs most potential reviewers will not end up seeing it, or realise that it is complete until then.

**Comment by pevogam** [comment]
> You'll need to tag that issue with awaiting-review if you want it to show up on the review queue that people look at (see https://leanprover-community.github.io/contribute/index.html#lifecycle-of-a-pr). As there are ~600 open PRs most potential reviewers will not end up seeing it, or realise that it is complete and ready for review until then.

As a contributor I don't think I have the necessary permissions to set labels on pull requests - in fact the link you shared confirms this and suggests that I should first ask for a write access? This might be a bit of an overkill for the contribution size but in any case thank you for the hints and pointers.

**Comment by alexjbest** [comment]
Yeah that is another issue with PRing from forks, I forgot about that too.

I do think it would be valuable to make the contribution process for small doc changes easier, it would probably allow more people to get started contributing that may not otherwise. @semorrison what do you think of adding the std / core "comment to add label" action to mathlib (if it isn't already) and explicitly spelling out that the if someone wants to make a quick doc edit they can do so in this way (and add the label) without having to join zulip state their plans and wait to be approved?
