### ISSUE TITLE
Set theory notation

### ISSUE THREAD

**Issue by djvelleman** [leanprover-community/mathlib4#754]
I'd like to suggest adding the following to Mathlib.Init.Set.lean:
```
macro (priority := low-1) "{ " pat:term " : " t:term " | " p:term " }" : term =>
  `({x : $t | match x with | $pat => $p})

macro (priority := low-1) "{ " pat:term " | " p:term " }" : term =>
  `({x | match x with | $pat => $p})

@[app_unexpander setOf]
def setOf.unexpander : Lean.PrettyPrinter.Unexpander
  | `($_ fun $_:ident =>
        match $_:ident with
        | $pat => $p) => `({ $pat:term | $p:term })
  | _ => throw ()
```
This allows set theory notation like `{(a, b) : Nat × Nat | a < b}`.
I have set the priority lower than all other set theory notation defined in Mathlib.Init.Set.lean, so this shouldn't interfere with any existing notation.

**Comment by djvelleman** [comment]
By the way, I'm not sure if I got the unexpander right; I didn't know how to specify that the two `ident`s should be the same.

**Comment by djvelleman** [comment]
Perhaps the unexpander needs to be written like this:
```
@[app_unexpander setOf]
def setOf.unexpander : Lean.PrettyPrinter.Unexpander
  | `($_ fun $x:ident => match $y:ident with | $pat => $p) =>
      if x.raw.getId = y.raw.getId then
        `({ $pat:term | $p:term })
      else
        throw ()
  | _ => throw ()
```

**Comment by kmill** [comment]
Closing as completed by #8850
