### ISSUE TITLE
example in Mathematics in Lean pdf uses "constructor" which isn't introduced until later

### ISSUE THREAD

**Issue by pine-leaf** [leanprover-community/mathlib4#7802]
The pdf _Mathematics in Lean_, release 0.1 on page 17, right above the beginning of section 2.4, has an example:
```lean
example : |a * b| ≤ (a^2 + b^2)/2 := by
  sorry

#check abs_le'.mpr
```
The solution given uses `constructor`, but that isn't introduced until chapter 3.

**Comment by robertylewis** [comment]
Thanks! This issue is tracked at https://github.com/avigad/mathematics_in_lean_source/issues/138 in the Mathematics in Lean repository.
