### ISSUE TITLE
Data/Fin: Create a lemma `Fin.forall_fin_succAbove`, analogous to Fin.forall_fin_succ, but using `Fin.succAbove`

### ISSUE THREAD

**Issue by BoltonBailey** [leanprover-community/mathlib4#8018]

**Comment by urkud** [comment]
We already have [Fin.forall_iff_succAbove](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Data/Fin/Tuple/Basic.html#Fin.forall_iff_succAbove).

**Comment by BoltonBailey** [comment]
Well, someone should make the name line up then.
