### ISSUE TITLE
Implement norm_num for `rpow`

### ISSUE THREAD

**Issue by eric-wieser** [leanprover-community/mathlib4#8828]
https://github.com/leanprover-community/mathlib4/blob/34bb97b7e04cdf4847b9ae20a23d56f7fc4d43e7/Mathlib/Analysis/SpecialFunctions/Pow/Real.lean#L816-L863

**Comment by dwrensha** [comment]
Implemented in #9893.

**Comment by dwrensha** [comment]
Closed by #9893.
