### ISSUE TITLE
to_additive interacts poorly with default fields of structures

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover-community/mathlib4#939]
See first item in https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Algebra.2EGroup.2EOpposite

**Comment by kbuzzard** [comment]
Note that the same `(kernel) invalid projection  blah.1` error (but with a different workaround) shows up here https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/to_additive.20failure/near/315154311 .
