### ISSUE TITLE
Testing slowdown

### ISSUE THREAD

**Issue by Parcly-Taxel** [leanprover-community/mathlib4#9999]
Zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Testing.20slowdown/near/417549488

Testing mathlib is currently significantly slower than before; it now takes about 4 minutes rather than 1.5 at most before #9828 was merged.

**Comment by semorrison** [comment]
testing mathlib is back down under 1 minute in CI, so I'm closing.
